/**
 * Unhappy path for the checkout functionality.  
 * This test is to verify that a user cannot purchase an item without a street address.
 * This test calls a special function that inputs all the requied information except for the street address. 
 */

 const CheckoutPage = require('../pageobjects/checkout.page');
 const ProductPage = require('../pageobjects/product.page');
 const CartPage = require('../pageobjects/cart.page'); 
 const { faker } = require('@faker-js/faker');
 
 describe('Unhappy Checkout functionality', () => {
     it('should fail to purchase item without street address', async () => {
         
         /**
          * Data for this test was generated by the faker module. 
          * The block below generates and assigns relevant fake information to variables needed for the unhappyCheckOut() function.  
          */
          const email = faker.internet.email(undefined,undefined,'gmail.com');
          const firstName = faker.name.firstName();
          const lastName = faker.name.lastName();
          const company = faker.company.name(); 
          const city = faker.address.city();
          const state = faker.address.state();
          //assign faker modules for the rest of the hard coded stuff below. 
         
         await ProductPage.open();
         await ProductPage.AddToCart(); 
         await CartPage.openCart();
         await CartPage.btnProceedCheckout.click(); 
         await CheckoutPage.unhappyCheckOut(email, firstName, lastName, company, city, state, '12134', 'United States', '8882255577');
         await expect(browser).toHaveUrl('https://magento.softwaretestingboard.com/checkout/#shipping'); 
 
     });
 });